/**
 * Design Tokens
 * 자동 생성된 파일 - 수동으로 수정하지 마세요
 * 
 * @generated by Style Dictionary
 * @see https://github.com/amzn/style-dictionary
 */

import { createGlobalTheme } from '@vanilla-extract/css';

export const tokens = createGlobalTheme(':root', {
  "neutral_gray": {
    "dn_white": "#ffffff",
    "dn_blue_gray_100": "#f9fafc",
    "dn_blue_gray_200": "#f1f3f7",
    "dn_blue_gray_300": "#e2e5eb",
    "dn_blue_gray_400": "#c8ccd7",
    "dn_blue_gray_500": "#a8afbd",
    "dn_blue_gray_600": "#8993a6",
    "dn_blue_gray_700": "#6e7688",
    "dn_blue_gray_800": "#495267",
    "dn_blue_gray_900": "#2d3548",
    "dn_black": "#000000"
  },
  "blue_colors": {
    "dn_blue_100": "#f0f7ff",
    "dn_blue_200": "#dcebff",
    "dn_blue_300": "#b6d4ff",
    "dn_blue_400": "#7fb3ff",
    "dn_blue_500": "#4792ff",
    "dn_blue_600": "#0f71ff",
    "dn_blue_700": "#004bcc",
    "dn_blue_800": "#0030a8"
  },
  "status_colors": {
    "dn_green_200": "#09c970",
    "dn_yellow_100": "#ffe522",
    "dn_skyblue_100": "#57a5ff",
    "dn_red_200": "#fc342a"
  },
  "accent_colors": {
    "dn_green_100": "#00c8c2",
    "dn_green_200": "#09c970",
    "dn_yellow_100": "#ffd119",
    "dn_yellow_200": "#ffb922",
    "dn_red_100": "#ff9a95",
    "dn_pink_100": "#f544c6",
    "dn_skyblue_100": "#57a5ff",
    "dn_darkblue_100": "#0055dd",
    "dn_purple_100": "#705bf7"
  },
  "fontfamilies": {
    "pretendard": "Pretendard"
  },
  "lineheights": {
    "0": "AUTO",
    "1": "AUTO",
    "2": "AUTO",
    "3": "AUTO",
    "4": "AUTO",
    "5": "AUTO",
    "6": "AUTO",
    "7": "AUTO",
    "8": "AUTO",
    "9": "AUTO",
    "10": "AUTO",
    "11": "AUTO",
    "12": "AUTO",
    "13": "AUTO",
    "14": "AUTO",
    "15": "AUTO",
    "16": "AUTO",
    "17": "AUTO",
    "18": "AUTO",
    "19": "AUTO",
    "20": "AUTO"
  },
  "fontweights": {
    "pretendard_0": "Bold",
    "pretendard_1": "Regular"
  },
  "fontsize": {
    "5": "16",
    "6": "14",
    "7": "16",
    "8": "16",
    "9": "14",
    "10": "14",
    "11": "12",
    "12": "12",
    "13": "16",
    "14": "16",
    "15": "14",
    "16": "14",
    "17": "12",
    "18": "12",
    "19": "14",
    "20": "12",
    "dn_font_headline_lg": "36",
    "dn_font_headline_md": "30",
    "dn_font_headline_sm": "22",
    "dn_font_title_xl": "20",
    "dn_font_title_lg": "18"
  },
  "letterspacing": {
    "0": "0%",
    "1": "0%",
    "2": "0%",
    "3": "0%",
    "4": "0%",
    "5": "0%",
    "6": "0%",
    "7": "0%",
    "8": "0%",
    "9": "0%",
    "10": "0%",
    "11": "0%",
    "12": "0%",
    "13": "0%",
    "14": "0%",
    "15": "0%",
    "16": "0%",
    "17": "0%",
    "18": "0%",
    "19": "0%",
    "20": "0%"
  },
  "paragraphspacing": {
    "0": "0",
    "1": "0",
    "2": "0",
    "3": "0",
    "4": "0",
    "5": "0",
    "6": "0",
    "7": "0",
    "8": "0",
    "9": "0",
    "10": "0",
    "11": "0",
    "12": "0",
    "13": "0",
    "14": "0",
    "15": "0",
    "16": "0",
    "17": "0",
    "18": "0",
    "19": "0",
    "20": "0"
  },
  "headline": {
    "lg": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "36px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "30px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "22px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "title": {
    "xl": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "20px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "18px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "body": {
    "lg_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "label": {
    "lg_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "caption": {
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "textcase": {
    "none": "none"
  },
  "textdecoration": {
    "none": "none"
  },
  "paragraphindent": {
    "0": "0px"
  }
});

