/**
 * Design Tokens
 * 자동 생성된 파일 - 수동으로 수정하지 마세요
 * 
 * @generated by Style Dictionary
 * @see https://github.com/amzn/style-dictionary
 */

import { createGlobalTheme } from '@vanilla-extract/css';

export const tokens = createGlobalTheme(':root', {
  "dds_tokens_default": {
    "color": {
      "neutral_gray": {
        "dn_white": "#ffffff",
        "dn_blue_gray_100": "#f9fafc",
        "dn_blue_gray_200": "#f1f3f7",
        "dn_blue_gray_300": "#e2e5eb",
        "dn_blue_gray_400": "#c8ccd7",
        "dn_blue_gray_500": "#a8afbd",
        "dn_blue_gray_600": "#8993a6",
        "dn_blue_gray_700": "#6e7688",
        "dn_blue_gray_800": "#495267",
        "dn_blue_gray_900": "#2d3548",
        "dn_black": "#000000"
      },
      "blue_colors": {
        "dn_blue_100": "#f0f7ff",
        "dn_blue_200": "#dcebff",
        "dn_blue_300": "#b6d4ff",
        "dn_blue_400": "#7fb3ff",
        "dn_blue_500": "#4792ff",
        "dn_blue_600": "#0f71ff",
        "dn_blue_700": "#004bcc",
        "dn_blue_800": "#0030a8"
      },
      "status_colors": {
        "dn_green_200": "#09c970",
        "dn_yellow_100": "#ffe522",
        "dn_skyblue_100": "#57a5ff",
        "dn_red_200": "#fc342a"
      },
      "accent_colors": {
        "dn_green_100": "#effef5",
        "dn_green_200": "#89de9e",
        "dn_yellow_100": "#fffce8",
        "dn_yellow_200": "#ffe96d",
        "dn_red_100": "#ffefef",
        "dn_pink_100": "#ffeffa",
        "dn_skyblue_100": "#57a5ff",
        "dn_darkblue_100": "#0055dd",
        "dn_purple_100": "#f7f1ff",
        "dn_green_300": "#04b060",
        "dn_mint_100": "#effefc",
        "dn_mint_300": "#00b7c4",
        "dn_yellow_300": "#ffb700",
        "dn_red_200": "#ffb7b3",
        "dn_red_300": "#f00b00",
        "dn_pink_200": "#ffb8ec",
        "dn_pink_300": "#f544c6",
        "dn_purple_200": "#ccb7ff",
        "dn_purple_300": "#705bf7",
        "dn_mint_200": "#96e8e6"
      }
    },
    "typography": {
      "fontfamily": {
        "pretendard": "Pretendard",
        "malgun_gothic": "Malgun Gothic",
        "roboto": "Roboto"
      },
      "fontweights": {
        "dn_font_weight_bold": "Bold",
        "dn_font_weight_regular": "Regular",
        "dn_font_weight_semibold": "Semibold",
        "dn_font_weight_medium": "Medium"
      },
      "fontsize": {
        "dn_font_size_xxl": "30",
        "dn_font_size_xl": "22",
        "dn_font_size_lg": "20",
        "dn_font_size_md": "18",
        "dn_font_size_sm": "16",
        "dn_font_size_xs": "14",
        "dn_font_size_xxs": "12",
        "dn_font_size_xxxl": "36"
      },
      "letter_spacing": {
        "dn_letter_spacing_tight": "-0.25",
        "dn_letter_spacing_normal": "0",
        "dn_letter_spacing_wide_sm": "0.25",
        "dn_letter_spacing_wide_md": "0.5",
        "dn_letter_spacing_wide_lg": "1"
      },
      "lineheights": {
        "dn_line_height_tight": "19",
        "dn_line_height_normal": "22",
        "dn_line_height_relaxed": "26",
        "dn_line_height_loose": "29"
      }
    },
    "radius": {
      "dn_radius_none": "0",
      "dn_radius_xs": "2",
      "dn_radius_sm": "4",
      "dn_radius_md": "6",
      "dn_radius_lg": "8",
      "dn_radius_xl": "12",
      "dn_radius_full": "9999"
    }
  }
});

