/**
 * Design Tokens
 * 자동 생성된 파일 - 수동으로 수정하지 마세요
 * 
 * @generated by Style Dictionary
 * @see https://github.com/amzn/style-dictionary
 */

import { createGlobalTheme } from '@vanilla-extract/css';

export const tokens = createGlobalTheme(':root', {
  "neutral_gray": {
    "dn_white": "#ffffff",
    "dn_blue_gray_100": "#f9fafc",
    "dn_blue_gray_200": "#f1f3f7",
    "dn_blue_gray_300": "#e2e5eb",
    "dn_blue_gray_400": "#c8ccd7",
    "dn_blue_gray_500": "#a8afbd",
    "dn_blue_gray_600": "#8993a6",
    "dn_blue_gray_700": "#6e7688",
    "dn_blue_gray_800": "#495267",
    "dn_blue_gray_900": "#2d3548",
    "dn_black": "#000000"
  },
  "blue_colors": {
    "dn_blue_100": "#f0f7ff",
    "dn_blue_200": "#dcebff",
    "dn_blue_300": "#b6d4ff",
    "dn_blue_400": "#7fb3ff",
    "dn_blue_500": "#4792ff",
    "dn_blue_600": "#0f71ff",
    "dn_blue_700": "#004bcc",
    "dn_blue_800": "#0030a8"
  },
  "status_colors": {
    "dn_green_200": "#09c970",
    "dn_yellow_100": "#ffe522",
    "dn_skyblue_100": "#57a5ff",
    "dn_red_200": "#fc342a"
  },
  "accent_colors": {
    "dn_green_100": "#00c8c2",
    "dn_green_200": "#09c970",
    "dn_yellow_100": "#ffd119",
    "dn_yellow_200": "#ffb922",
    "dn_red_100": "#ff9a95",
    "dn_pink_100": "#f544c6",
    "dn_skyblue_100": "#57a5ff",
    "dn_darkblue_100": "#0055dd",
    "dn_purple_100": "#705bf7"
  },
  "fontfamilies": {
    "pretendard": "Pretendard"
  },
  "lineheights": {
    "0": "AUTO",
    "1": "AUTO",
    "2": "AUTO",
    "3": "AUTO",
    "4": "AUTO",
    "5": "AUTO",
    "6": "AUTO",
    "7": "AUTO",
    "8": "AUTO",
    "9": "AUTO",
    "10": "AUTO",
    "11": "AUTO",
    "12": "AUTO",
    "13": "AUTO",
    "14": "AUTO",
    "15": "AUTO",
    "16": "AUTO",
    "17": "AUTO",
    "18": "AUTO",
    "19": "AUTO",
    "20": "AUTO"
  },
  "fontweights": {
    "pretendard_0": "Bold",
    "pretendard_1": "Regular"
  },
  "fontsize": {
    "0": "36",
    "1": "30",
    "2": "22",
    "3": "20",
    "4": "18",
    "5": "16",
    "6": "14",
    "7": "16",
    "8": "16",
    "9": "14",
    "10": "14",
    "11": "12",
    "12": "12",
    "13": "16",
    "14": "16",
    "15": "14",
    "16": "14",
    "17": "12",
    "18": "12",
    "19": "14",
    "20": "12"
  },
  "letterspacing": {
    "0": "0%",
    "1": "0%",
    "2": "0%",
    "3": "0%",
    "4": "0%",
    "5": "0%",
    "6": "0%",
    "7": "0%",
    "8": "0%",
    "9": "0%",
    "10": "0%",
    "11": "0%",
    "12": "0%",
    "13": "0%",
    "14": "0%",
    "15": "0%",
    "16": "0%",
    "17": "0%",
    "18": "0%",
    "19": "0%",
    "20": "0%"
  },
  "paragraphspacing": {
    "0": "0",
    "1": "0",
    "2": "0",
    "3": "0",
    "4": "0",
    "5": "0",
    "6": "0",
    "7": "0",
    "8": "0",
    "9": "0",
    "10": "0",
    "11": "0",
    "12": "0",
    "13": "0",
    "14": "0",
    "15": "0",
    "16": "0",
    "17": "0",
    "18": "0",
    "19": "0",
    "20": "0"
  },
  "headline": {
    "lg": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "36px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "30px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "22px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "title": {
    "xl": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "20px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "18px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "body": {
    "lg_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "label": {
    "lg_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "caption": {
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "textcase": {
    "none": "none"
  },
  "textdecoration": {
    "none": "none"
  },
  "paragraphindent": {
    "0": "0px"
  }
});

/**
 * TypeScript 타입 정의
 */
export interface TokensType {
  'neutral_gray.dn_white'?: string;
  'neutral_gray.dn_blue_gray_100'?: string;
  'neutral_gray.dn_blue_gray_200'?: string;
  'neutral_gray.dn_blue_gray_300'?: string;
  'neutral_gray.dn_blue_gray_400'?: string;
  'neutral_gray.dn_blue_gray_500'?: string;
  'neutral_gray.dn_blue_gray_600'?: string;
  'neutral_gray.dn_blue_gray_700'?: string;
  'neutral_gray.dn_blue_gray_800'?: string;
  'neutral_gray.dn_blue_gray_900'?: string;
  'neutral_gray.dn_black'?: string;
  'blue_colors.dn_blue_100'?: string;
  'blue_colors.dn_blue_200'?: string;
  'blue_colors.dn_blue_300'?: string;
  'blue_colors.dn_blue_400'?: string;
  'blue_colors.dn_blue_500'?: string;
  'blue_colors.dn_blue_600'?: string;
  'blue_colors.dn_blue_700'?: string;
  'blue_colors.dn_blue_800'?: string;
  'status_colors.dn_green_200'?: string;
  'status_colors.dn_yellow_100'?: string;
  'status_colors.dn_skyblue_100'?: string;
  'status_colors.dn_red_200'?: string;
  'accent_colors.dn_green_100'?: string;
  'accent_colors.dn_green_200'?: string;
  'accent_colors.dn_yellow_100'?: string;
  'accent_colors.dn_yellow_200'?: string;
  'accent_colors.dn_red_100'?: string;
  'accent_colors.dn_pink_100'?: string;
  'accent_colors.dn_skyblue_100'?: string;
  'accent_colors.dn_darkblue_100'?: string;
  'accent_colors.dn_purple_100'?: string;
  'fontfamilies.pretendard'?: string;
  'lineheights.0'?: string;
  'lineheights.1'?: string;
  'lineheights.2'?: string;
  'lineheights.3'?: string;
  'lineheights.4'?: string;
  'lineheights.5'?: string;
  'lineheights.6'?: string;
  'lineheights.7'?: string;
  'lineheights.8'?: string;
  'lineheights.9'?: string;
  'lineheights.10'?: string;
  'lineheights.11'?: string;
  'lineheights.12'?: string;
  'lineheights.13'?: string;
  'lineheights.14'?: string;
  'lineheights.15'?: string;
  'lineheights.16'?: string;
  'lineheights.17'?: string;
  'lineheights.18'?: string;
  'lineheights.19'?: string;
  'lineheights.20'?: string;
  'fontweights.pretendard_0'?: string;
  'fontweights.pretendard_1'?: string;
  'fontsize.0'?: string;
  'fontsize.1'?: string;
  'fontsize.2'?: string;
  'fontsize.3'?: string;
  'fontsize.4'?: string;
  'fontsize.5'?: string;
  'fontsize.6'?: string;
  'fontsize.7'?: string;
  'fontsize.8'?: string;
  'fontsize.9'?: string;
  'fontsize.10'?: string;
  'fontsize.11'?: string;
  'fontsize.12'?: string;
  'fontsize.13'?: string;
  'fontsize.14'?: string;
  'fontsize.15'?: string;
  'fontsize.16'?: string;
  'fontsize.17'?: string;
  'fontsize.18'?: string;
  'fontsize.19'?: string;
  'fontsize.20'?: string;
  'letterspacing.0'?: string;
  'letterspacing.1'?: string;
  'letterspacing.2'?: string;
  'letterspacing.3'?: string;
  'letterspacing.4'?: string;
  'letterspacing.5'?: string;
  'letterspacing.6'?: string;
  'letterspacing.7'?: string;
  'letterspacing.8'?: string;
  'letterspacing.9'?: string;
  'letterspacing.10'?: string;
  'letterspacing.11'?: string;
  'letterspacing.12'?: string;
  'letterspacing.13'?: string;
  'letterspacing.14'?: string;
  'letterspacing.15'?: string;
  'letterspacing.16'?: string;
  'letterspacing.17'?: string;
  'letterspacing.18'?: string;
  'letterspacing.19'?: string;
  'letterspacing.20'?: string;
  'paragraphspacing.0'?: string;
  'paragraphspacing.1'?: string;
  'paragraphspacing.2'?: string;
  'paragraphspacing.3'?: string;
  'paragraphspacing.4'?: string;
  'paragraphspacing.5'?: string;
  'paragraphspacing.6'?: string;
  'paragraphspacing.7'?: string;
  'paragraphspacing.8'?: string;
  'paragraphspacing.9'?: string;
  'paragraphspacing.10'?: string;
  'paragraphspacing.11'?: string;
  'paragraphspacing.12'?: string;
  'paragraphspacing.13'?: string;
  'paragraphspacing.14'?: string;
  'paragraphspacing.15'?: string;
  'paragraphspacing.16'?: string;
  'paragraphspacing.17'?: string;
  'paragraphspacing.18'?: string;
  'paragraphspacing.19'?: string;
  'paragraphspacing.20'?: string;
  'headline.lg.fontFamily'?: string;
  'headline.lg.fontWeight'?: string;
  'headline.lg.lineHeight'?: string;
  'headline.lg.fontSize'?: string;
  'headline.lg.letterSpacing'?: string;
  'headline.lg.paragraphSpacing'?: string;
  'headline.lg.paragraphIndent'?: string;
  'headline.lg.textCase'?: string;
  'headline.lg.textDecoration'?: string;
  'headline.md.fontFamily'?: string;
  'headline.md.fontWeight'?: string;
  'headline.md.lineHeight'?: string;
  'headline.md.fontSize'?: string;
  'headline.md.letterSpacing'?: string;
  'headline.md.paragraphSpacing'?: string;
  'headline.md.paragraphIndent'?: string;
  'headline.md.textCase'?: string;
  'headline.md.textDecoration'?: string;
  'headline.sm.fontFamily'?: string;
  'headline.sm.fontWeight'?: string;
  'headline.sm.lineHeight'?: string;
  'headline.sm.fontSize'?: string;
  'headline.sm.letterSpacing'?: string;
  'headline.sm.paragraphSpacing'?: string;
  'headline.sm.paragraphIndent'?: string;
  'headline.sm.textCase'?: string;
  'headline.sm.textDecoration'?: string;
  'title.xl.fontFamily'?: string;
  'title.xl.fontWeight'?: string;
  'title.xl.lineHeight'?: string;
  'title.xl.fontSize'?: string;
  'title.xl.letterSpacing'?: string;
  'title.xl.paragraphSpacing'?: string;
  'title.xl.paragraphIndent'?: string;
  'title.xl.textCase'?: string;
  'title.xl.textDecoration'?: string;
  'title.lg.fontFamily'?: string;
  'title.lg.fontWeight'?: string;
  'title.lg.lineHeight'?: string;
  'title.lg.fontSize'?: string;
  'title.lg.letterSpacing'?: string;
  'title.lg.paragraphSpacing'?: string;
  'title.lg.paragraphIndent'?: string;
  'title.lg.textCase'?: string;
  'title.lg.textDecoration'?: string;
  'title.md.fontFamily'?: string;
  'title.md.fontWeight'?: string;
  'title.md.lineHeight'?: string;
  'title.md.fontSize'?: string;
  'title.md.letterSpacing'?: string;
  'title.md.paragraphSpacing'?: string;
  'title.md.paragraphIndent'?: string;
  'title.md.textCase'?: string;
  'title.md.textDecoration'?: string;
  'title.sm.fontFamily'?: string;
  'title.sm.fontWeight'?: string;
  'title.sm.lineHeight'?: string;
  'title.sm.fontSize'?: string;
  'title.sm.letterSpacing'?: string;
  'title.sm.paragraphSpacing'?: string;
  'title.sm.paragraphIndent'?: string;
  'title.sm.textCase'?: string;
  'title.sm.textDecoration'?: string;
  'body.lg_bold.fontFamily'?: string;
  'body.lg_bold.fontWeight'?: string;
  'body.lg_bold.lineHeight'?: string;
  'body.lg_bold.fontSize'?: string;
  'body.lg_bold.letterSpacing'?: string;
  'body.lg_bold.paragraphSpacing'?: string;
  'body.lg_bold.paragraphIndent'?: string;
  'body.lg_bold.textCase'?: string;
  'body.lg_bold.textDecoration'?: string;
  'body.lg_regular.fontFamily'?: string;
  'body.lg_regular.fontWeight'?: string;
  'body.lg_regular.lineHeight'?: string;
  'body.lg_regular.fontSize'?: string;
  'body.lg_regular.letterSpacing'?: string;
  'body.lg_regular.paragraphSpacing'?: string;
  'body.lg_regular.paragraphIndent'?: string;
  'body.lg_regular.textCase'?: string;
  'body.lg_regular.textDecoration'?: string;
  'body.md_bold.fontFamily'?: string;
  'body.md_bold.fontWeight'?: string;
  'body.md_bold.lineHeight'?: string;
  'body.md_bold.fontSize'?: string;
  'body.md_bold.letterSpacing'?: string;
  'body.md_bold.paragraphSpacing'?: string;
  'body.md_bold.paragraphIndent'?: string;
  'body.md_bold.textCase'?: string;
  'body.md_bold.textDecoration'?: string;
  'body.md_regular.fontFamily'?: string;
  'body.md_regular.fontWeight'?: string;
  'body.md_regular.lineHeight'?: string;
  'body.md_regular.fontSize'?: string;
  'body.md_regular.letterSpacing'?: string;
  'body.md_regular.paragraphSpacing'?: string;
  'body.md_regular.paragraphIndent'?: string;
  'body.md_regular.textCase'?: string;
  'body.md_regular.textDecoration'?: string;
  'body.sm_bold.fontFamily'?: string;
  'body.sm_bold.fontWeight'?: string;
  'body.sm_bold.lineHeight'?: string;
  'body.sm_bold.fontSize'?: string;
  'body.sm_bold.letterSpacing'?: string;
  'body.sm_bold.paragraphSpacing'?: string;
  'body.sm_bold.paragraphIndent'?: string;
  'body.sm_bold.textCase'?: string;
  'body.sm_bold.textDecoration'?: string;
  'body.sm_regular.fontFamily'?: string;
  'body.sm_regular.fontWeight'?: string;
  'body.sm_regular.lineHeight'?: string;
  'body.sm_regular.fontSize'?: string;
  'body.sm_regular.letterSpacing'?: string;
  'body.sm_regular.paragraphSpacing'?: string;
  'body.sm_regular.paragraphIndent'?: string;
  'body.sm_regular.textCase'?: string;
  'body.sm_regular.textDecoration'?: string;
  'label.lg_bold.fontFamily'?: string;
  'label.lg_bold.fontWeight'?: string;
  'label.lg_bold.lineHeight'?: string;
  'label.lg_bold.fontSize'?: string;
  'label.lg_bold.letterSpacing'?: string;
  'label.lg_bold.paragraphSpacing'?: string;
  'label.lg_bold.paragraphIndent'?: string;
  'label.lg_bold.textCase'?: string;
  'label.lg_bold.textDecoration'?: string;
  'label.lg_regular.fontFamily'?: string;
  'label.lg_regular.fontWeight'?: string;
  'label.lg_regular.lineHeight'?: string;
  'label.lg_regular.fontSize'?: string;
  'label.lg_regular.letterSpacing'?: string;
  'label.lg_regular.paragraphSpacing'?: string;
  'label.lg_regular.paragraphIndent'?: string;
  'label.lg_regular.textCase'?: string;
  'label.lg_regular.textDecoration'?: string;
  'label.md_bold.fontFamily'?: string;
  'label.md_bold.fontWeight'?: string;
  'label.md_bold.lineHeight'?: string;
  'label.md_bold.fontSize'?: string;
  'label.md_bold.letterSpacing'?: string;
  'label.md_bold.paragraphSpacing'?: string;
  'label.md_bold.paragraphIndent'?: string;
  'label.md_bold.textCase'?: string;
  'label.md_bold.textDecoration'?: string;
  'label.md_regular.fontFamily'?: string;
  'label.md_regular.fontWeight'?: string;
  'label.md_regular.lineHeight'?: string;
  'label.md_regular.fontSize'?: string;
  'label.md_regular.letterSpacing'?: string;
  'label.md_regular.paragraphSpacing'?: string;
  'label.md_regular.paragraphIndent'?: string;
  'label.md_regular.textCase'?: string;
  'label.md_regular.textDecoration'?: string;
  'label.sm_bold.fontFamily'?: string;
  'label.sm_bold.fontWeight'?: string;
  'label.sm_bold.lineHeight'?: string;
  'label.sm_bold.fontSize'?: string;
  'label.sm_bold.letterSpacing'?: string;
  'label.sm_bold.paragraphSpacing'?: string;
  'label.sm_bold.paragraphIndent'?: string;
  'label.sm_bold.textCase'?: string;
  'label.sm_bold.textDecoration'?: string;
  'label.sm_regular.fontFamily'?: string;
  'label.sm_regular.fontWeight'?: string;
  'label.sm_regular.lineHeight'?: string;
  'label.sm_regular.fontSize'?: string;
  'label.sm_regular.letterSpacing'?: string;
  'label.sm_regular.paragraphSpacing'?: string;
  'label.sm_regular.paragraphIndent'?: string;
  'label.sm_regular.textCase'?: string;
  'label.sm_regular.textDecoration'?: string;
  'caption.md_regular.fontFamily'?: string;
  'caption.md_regular.fontWeight'?: string;
  'caption.md_regular.lineHeight'?: string;
  'caption.md_regular.fontSize'?: string;
  'caption.md_regular.letterSpacing'?: string;
  'caption.md_regular.paragraphSpacing'?: string;
  'caption.md_regular.paragraphIndent'?: string;
  'caption.md_regular.textCase'?: string;
  'caption.md_regular.textDecoration'?: string;
  'caption.sm_regular.fontFamily'?: string;
  'caption.sm_regular.fontWeight'?: string;
  'caption.sm_regular.lineHeight'?: string;
  'caption.sm_regular.fontSize'?: string;
  'caption.sm_regular.letterSpacing'?: string;
  'caption.sm_regular.paragraphSpacing'?: string;
  'caption.sm_regular.paragraphIndent'?: string;
  'caption.sm_regular.textCase'?: string;
  'caption.sm_regular.textDecoration'?: string;
  'textcase.none'?: string;
  'textdecoration.none'?: string;
  'paragraphindent.0'?: string;
}

/**
 * 런타임 타입
 */
export type Tokens = typeof tokens;

/**
 * 토큰 접근을 위한 유틸리티 함수 (타입 안전)
 */
export const getToken = <T extends keyof TokensType>(path: T): string => {
  const keys = String(path).split('.');
  let value: any = tokens;
  
  for (const key of keys) {
    value = value?.[key];
    if (value === undefined) {
      console.warn(`Token not found: ${String(path)}`);
      return '';
    }
  }
  
  return value;
};

/**
 * 토큰 맵 (자동완성 지원)
 */
export const tokenMap = {
  "neutral_gray": {
    "dn_white": "#ffffff",
    "dn_blue_gray_100": "#f9fafc",
    "dn_blue_gray_200": "#f1f3f7",
    "dn_blue_gray_300": "#e2e5eb",
    "dn_blue_gray_400": "#c8ccd7",
    "dn_blue_gray_500": "#a8afbd",
    "dn_blue_gray_600": "#8993a6",
    "dn_blue_gray_700": "#6e7688",
    "dn_blue_gray_800": "#495267",
    "dn_blue_gray_900": "#2d3548",
    "dn_black": "#000000"
  },
  "blue_colors": {
    "dn_blue_100": "#f0f7ff",
    "dn_blue_200": "#dcebff",
    "dn_blue_300": "#b6d4ff",
    "dn_blue_400": "#7fb3ff",
    "dn_blue_500": "#4792ff",
    "dn_blue_600": "#0f71ff",
    "dn_blue_700": "#004bcc",
    "dn_blue_800": "#0030a8"
  },
  "status_colors": {
    "dn_green_200": "#09c970",
    "dn_yellow_100": "#ffe522",
    "dn_skyblue_100": "#57a5ff",
    "dn_red_200": "#fc342a"
  },
  "accent_colors": {
    "dn_green_100": "#00c8c2",
    "dn_green_200": "#09c970",
    "dn_yellow_100": "#ffd119",
    "dn_yellow_200": "#ffb922",
    "dn_red_100": "#ff9a95",
    "dn_pink_100": "#f544c6",
    "dn_skyblue_100": "#57a5ff",
    "dn_darkblue_100": "#0055dd",
    "dn_purple_100": "#705bf7"
  },
  "fontfamilies": {
    "pretendard": "Pretendard"
  },
  "lineheights": {
    "0": "AUTO",
    "1": "AUTO",
    "2": "AUTO",
    "3": "AUTO",
    "4": "AUTO",
    "5": "AUTO",
    "6": "AUTO",
    "7": "AUTO",
    "8": "AUTO",
    "9": "AUTO",
    "10": "AUTO",
    "11": "AUTO",
    "12": "AUTO",
    "13": "AUTO",
    "14": "AUTO",
    "15": "AUTO",
    "16": "AUTO",
    "17": "AUTO",
    "18": "AUTO",
    "19": "AUTO",
    "20": "AUTO"
  },
  "fontweights": {
    "pretendard_0": "Bold",
    "pretendard_1": "Regular"
  },
  "fontsize": {
    "0": "36",
    "1": "30",
    "2": "22",
    "3": "20",
    "4": "18",
    "5": "16",
    "6": "14",
    "7": "16",
    "8": "16",
    "9": "14",
    "10": "14",
    "11": "12",
    "12": "12",
    "13": "16",
    "14": "16",
    "15": "14",
    "16": "14",
    "17": "12",
    "18": "12",
    "19": "14",
    "20": "12"
  },
  "letterspacing": {
    "0": "0%",
    "1": "0%",
    "2": "0%",
    "3": "0%",
    "4": "0%",
    "5": "0%",
    "6": "0%",
    "7": "0%",
    "8": "0%",
    "9": "0%",
    "10": "0%",
    "11": "0%",
    "12": "0%",
    "13": "0%",
    "14": "0%",
    "15": "0%",
    "16": "0%",
    "17": "0%",
    "18": "0%",
    "19": "0%",
    "20": "0%"
  },
  "paragraphspacing": {
    "0": "0",
    "1": "0",
    "2": "0",
    "3": "0",
    "4": "0",
    "5": "0",
    "6": "0",
    "7": "0",
    "8": "0",
    "9": "0",
    "10": "0",
    "11": "0",
    "12": "0",
    "13": "0",
    "14": "0",
    "15": "0",
    "16": "0",
    "17": "0",
    "18": "0",
    "19": "0",
    "20": "0"
  },
  "headline": {
    "lg": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "36px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "30px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "22px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "title": {
    "xl": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "20px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "18px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "body": {
    "lg_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "label": {
    "lg_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "lg_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "16px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_bold": {
      "fontFamily": "Pretendard",
      "fontWeight": "Bold",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "caption": {
    "md_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "14px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "sm_regular": {
      "fontFamily": "Pretendard",
      "fontWeight": "Regular",
      "lineHeight": "AUTO",
      "fontSize": "12px",
      "letterSpacing": "0%",
      "paragraphSpacing": "0",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "textcase": {
    "none": "none"
  },
  "textdecoration": {
    "none": "none"
  },
  "paragraphindent": {
    "0": "0px"
  }
} as const;
